# Generated by Django 5.2 on 2025-09-23 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppCustomuser',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
                ('email', models.CharField(max_length=254, unique=True)),
                ('contact', models.CharField(max_length=15)),
                ('gender', models.TextField()),
                ('salary', models.FloatField(blank=True, null=True)),
                ('role', models.CharField(blank=True, max_length=200, null=True)),
                ('id_no', models.IntegerField(unique=True)),
            ],
            options={
                'db_table': 'app_customuser',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('inventory_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(blank=True, max_length=200, null=True)),
                ('category', models.CharField(blank=True, max_length=200, null=True)),
                ('service_time', models.TextField(blank=True, max_length=20, null=True)),
                ('item_description', models.TextField(blank=True, max_length=200, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('price_per_unit', models.FloatField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'Inventory',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_id', models.AutoField(primary_key=True, serialize=False)),
                ('room_type', models.CharField(max_length=200)),
                ('bed_type', models.CharField(max_length=200)),
                ('price_per_night', models.FloatField(max_length=200)),
                ('availabilty_status', models.IntegerField()),
                ('max_occupation', models.IntegerField()),
            ],
            options={
                'db_table': 'Room',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('check_in_date', models.TextField(blank=True, max_length=10, null=True)),
                ('check_out_date', models.TextField(blank=True, max_length=10, null=True)),
                ('number_of_guests', models.IntegerField(blank=True, null=True)),
                ('total_price', models.FloatField(blank=True, max_length=200, null=True)),
                ('booking_status', models.TextField(max_length=200)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.appcustomuser')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.room')),
            ],
            options={
                'db_table': 'Booking',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.FloatField(blank=True, max_length=200, null=True)),
                ('payment_time', models.TextField(blank=True, max_length=10, null=True)),
                ('payment_date', models.TextField(blank=True, max_length=10, null=True)),
                ('payment_mode', models.TextField(max_length=200)),
                ('account', models.IntegerField()),
                ('payment_status', models.TextField(max_length=200)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.booking')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.service')),
            ],
            options={
                'db_table': 'payment',
            },
        ),
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('request_time', models.TextField(blank=True, max_length=10, null=True)),
                ('request_date', models.TextField(blank=True, max_length=10, null=True)),
                ('request_status', models.TextField()),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.booking')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.service')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.appcustomuser')),
            ],
            options={
                'db_table': 'Service_request',
            },
        ),
    ]
