# Generated by Django 5.2 on 2025-09-24 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_payment_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={},
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payment_date',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='request_date',
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_status',
            field=models.TextField(default='active', max_length=200),
        ),
        migrations.AlterField(
            model_name='booking',
            name='check_out_date',
            field=models.DateField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='account',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_status',
            field=models.TextField(default='paid', max_length=200),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_time',
            field=models.DateTimeField(blank=True, default='2025-09-24 23:58:16.765274', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='request_status',
            field=models.TextField(default='pending', max_length=200),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='request_time',
            field=models.DateTimeField(blank=True, default='2025-09-24 23:58:16.764272', max_length=50, null=True),
        ),
    ]
