# Generated by Django 5.2 on 2025-10-20 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_service_options_remove_payment_payment_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_time',
            field=models.DateTimeField(blank=True, default='2025-10-20 16:21:58.351994', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='request_time',
            field=models.DateTimeField(blank=True, default='2025-10-20 16:21:58.350994', max_length=50, null=True),
        ),
    ]
