# Generated by Django 5.2 on 2025-10-20 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_payment_payment_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_time',
            field=models.DateTimeField(blank=True, default='2025-10-20 20:50:29.245009', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='request_time',
            field=models.DateTimeField(blank=True, default='2025-10-20 20:50:29.234999', max_length=50, null=True),
        ),
    ]
