# Generated by Django 5.2 on 2025-10-20 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_payment_payment_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='id_no',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_time',
            field=models.DateTimeField(blank=True, default='2025-10-20 21:05:07.024046', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='request_time',
            field=models.DateTimeField(blank=True, default='2025-10-20 21:05:07.023046', max_length=50, null=True),
        ),
    ]
