# Generated by Django 5.2 on 2025-11-04 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_customuser_id_no_alter_payment_payment_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_time',
            field=models.DateTimeField(blank=True, default='2025-11-04 10:12:38.810494', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='request_time',
            field=models.DateTimeField(blank=True, default='2025-11-04 10:12:38.809527', max_length=50, null=True),
        ),
    ]
