# Generated by Django 5.2 on 2025-11-04 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_payment_payment_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_time',
            field=models.DateTimeField(blank=True, default='2025-11-04 10:56:33.507382', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='request_time',
            field=models.DateTimeField(blank=True, default='2025-11-04 10:56:33.506424', max_length=50, null=True),
        ),
    ]
